apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deploy
  namespace: development
spec:
  replicas: 3
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: web-container
          # 🔁 Change image to trigger rollout
          image: httpd:2.4
          ports:
            - containerPort: 80
