apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-service
spec:
  type: ClusterIP  # Changed from LoadBalancer to ClusterIP
  selector:
    app: tic-tac-toe
  ports:
    - name: web
      protocol: TCP
      port: 80        # Exposed port within the cluster
      targetPort: 80  # Target port of the application

