apiVersion: v1
kind: Service
metadata:
  name: tic-tac-toe-service
  annotations:
    metallb.io/ip-allocated-from-pool: cluster-pool  # Ensure this matches your MetalLB pool
spec:
  type: LoadBalancer
  selector:
    app: tic-tac-toe
  ports:
    - name: web
      protocol: TCP
      port: 80        # Expose this port
      targetPort: 80  # Jenkins runs on 8080
      targetPort: 80 # For Jenkins agent communication
